<?php
// Variables
return [
  "creatorName" => 'afterd123',
  "creatorUrl" => 'https://afterdom.codingku2024.my.id',
  "templateName" => 'afterd',
  "templateSuffix" => 'Buy Sell Domain',
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => 'Buy Sell Domain',
  "templateKeyword" => 'Buy Domain, Sell Domain',
  "licenseUrl" => "https://afterdom.codingku2024.my.id",
  "livePreview" => "https://afterdom.codingku2024.my.id",
  "productPage" => "https://afterdom.codingku2024.my.id",
  "support" => "https://afterdom.codingku2024.my.id",
  "moreThemes" => "https://afterdom.codingku2024.my.id",
  "documentation" => "https://afterdom.codingku2024.my.id",
  "generator" => "",
  "changelog" => "https://afterdom.codingku2024.my.id",
  "repository" => "https://afterdom.codingku2024.my.id",
  "gitRepo" => "afterdom",
  "gitRepoAccess" => "afterdom",
  "githubFreeUrl" => "https://afterdom.codingku2024.my.id",
  "facebookUrl" => 'https://www.facebook.com/afterdom/',
  "twitterUrl" => 'https://twitter.com/afterdom',
  "githubUrl" => "https://github.com/afterdom",
  "dribbbleUrl" => "https://dribbble.com/afterdom",
  "instagramUrl" => 'https://www.instagram.com/afterdom/',
  "loginName" => 'Afterd123',
  "logo" => 'assets/img/logo.png',
  "DmerchantCode" => "DS19918",
  "DapiKey" => "6caf472c7a3e8f28fdcafb11a95db54d",
  "DurlMethod" => "https://sandbox.duitku.com/webapi/api/merchant/paymentmethod/getpaymentmethod",
  "DurlInquery" => "https://sandbox.duitku.com/webapi/api/merchant/v2/inquiry",
  "PClientID" => "AdvGQT2sszx0qEqitUAXZP_ZPyNSNOwPfZGqUoVosELs2RpEPvnv1gJ8Pjd9Cq-rFbFv0iwEBtkcL3Xk",
  "PSecret" => "EIbZY9HSfbuEuGvQnjTTdVaMyzfopupJVYne9RKpIPrkt12OAf5RphSyxcTsR4Q9BTJ-8JCh75NqyoTV",
  "PurlToken" => "https://api-m.sandbox.paypal.com/v1/oauth2/token",
  "PurlCheckout" => "https://api-m.sandbox.paypal.com/v2/checkout/orders",
  "minSaldoBid" => '30'
];
